=== luishidalgoo27/2T---Luis-Hidalgo/tema10/curso.dtd
<!ELEMENT listacursos (curso)>
<!ELEMENT curso (profesor,alumno,contenido)>
<!ATTLIST curso codigo NMTOKEN #REQUIRED>
<!ELEMENT profesor (dni,nombre,ap1,ap2)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ap1 (#PCDATA)>
<!ELEMENT ap2 (#PCDATA)>
<!ELEMENT alumno (dni,nombre,ap1)>
<!ELEMENT contenido (#PCDATA)>

=== luishidalgoo27/2T---Luis-Hidalgo/tema10/curso.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE listacursos SYSTEM "curso.dtd">
<listacursos>
    <curso codigo="LM">
        <profesor>
            <dni>30515455K</dni>
            <nombre>Tomás</nombre>
            <ap1>Martínez</ap1>
            <ap2>Ruiz</ap2>
        </profesor>
        <alumno>
            <dni>33354697A</dni>
            <nombre>Silvia</nombre>
            <ap1>Ruiz</ap1>
        </alumno>
        <contenido>Introducción a los lenguajes de marcas</contenido>
    </curso>
</listacursos>
