=== luishidalgoo27/2T---Luis-Hidalgo/tema10/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="numero" type="xs:string" />
                <xs:element name="fecha" type="xs:string" />
                <xs:element name="datosemisor">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empresa" type="xs:string" />
                            <xs:element name="cif" type="xs:string" />
                            <xs:element name="telefono" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datoscliente">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empresa" type="xs:string" />
                            <xs:element name="cif" type="xs:string" />
                            <xs:element name="telefono" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="detalles">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="detallefactura" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="descripcion" type="xs:string" />
                                        <xs:element name="cant" type="xs:string" />
                                        <xs:element name="oferta" type="xs:string" />
                                        <xs:element name="pvp" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="tipo" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="importe">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="pvp" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== luishidalgoo27/2T---Luis-Hidalgo/tema10/factura.xml
<?xml version="1.0" encoding="UTF-8"?>


<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="factura.xsd">
    <numero>Factura Numero 27</numero>
    <fecha>18/12/2013</fecha>
    <datosemisor>
        <empresa>Librería Pérez</empresa>
        <cif>44555666B</cif>
        <telefono>777888999</telefono>
    </datosemisor>
    <datoscliente>
        <empresa>Biblioteca Txantrea</empresa>
        <cif>33111222A</cif>
        <telefono>333999444</telefono>
    </datoscliente>
    <detalles>
    <detallefactura tipo="LIBRO">
        <descripcion>Analítica Web 2.0</descripcion>
        <cant>1</cant>
        <oferta>SI</oferta>
        <pvp>25€</pvp>
    </detallefactura>
    <detallefactura tipo="DVD">
        <descripcion>Curso de HTML</descripcion>
        <cant>2</cant>
        <oferta>NO</oferta>
        <pvp>30€</pvp>
    </detallefactura>
    <importe>
        <pvp>85€</pvp>
    </importe>
    </detalles>
</factura>
