=== luishidalgoo27/2T---Luis-Hidalgo/tema11/concesionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="concesionario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="coche" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string" />
                            <xs:element name="modelo" type="xs:string" />
                            <xs:choice>
                            <xs:element name="cilindrada" type="xs:decimal" />
                            <xs:element name="caballos" type="xs:unsignedShort" />
                            </xs:choice>
                            <xs:element name="combustible" type="xs:string" />
                            <xs:element name="precio" type="xs:string" />
                            <xs:element minOccurs="0" name="aÃ±o" type="xs:unsignedShort" />
                            <xs:element name="color" type="xs:string" />
                            <xs:element minOccurs="0" maxOccurs="unbounded" name="interesado" type="xs:string"/>
                            <xs:element minOccurs="0" name="fecha_limite">
                                <xs:complexType>
                                    <xs:attribute name="fecha" type="xs:date" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="matricula" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== luishidalgoo27/2T---Luis-Hidalgo/tema11/concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<concesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="concesionario.xsd">
<coche matricula="6732KPC">
    <marca>Seat</marca>
    <modelo>Ateca</modelo>
    <cilindrada>1.7</cilindrada>
    <combustible>Diesel</combustible>
    <precio>23.000€</precio>
    <año>2018</año>
    <color>Negro</color>
    <interesado>33358697A</interesado>
    <interesado>30515455T</interesado>
    <fecha_limite fecha="2022-02-12"/>
</coche>
<coche matricula="8280DGH">
    <marca>Volkswagen</marca>
    <modelo>Polo</modelo>
    <cilindrada>1.2</cilindrada>
    <combustible>Gasolina</combustible>
    <precio>5.000€</precio>
    <color>Rojo</color>
    <interesado>60514553T</interesado>
</coche>
<coche matricula="8765DHG">
    <marca>Renault</marca>
    <modelo>Megane</modelo>
    <caballos>120</caballos>
    <combustible>Diesel</combustible>
    <precio>7.500€</precio>
    <color>Verde</color>
</coche>
</concesionario>
