=== luishidalgoo27/2T---Luis-Hidalgo/tema11/concesionariooptimizado.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="coche">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="marca" type="xs:string" />
                <xs:element name="modelo" type="xs:string" />
                <xs:element name="cilindrada" type="xs:string" />
                <xs:element name="combustible" type="xs:string" />
                <xs:element name="precio" type="xs:string" />
                <xs:element name="aÃ±o" type="xs:string" />
                <xs:element name="color" type="xs:string" />
                <xs:element name="interesado" maxOccurs="unbounded" type="xs:string" />
                <xs:element name="fecha_limite">
                    <xs:complexType>
                        <xs:attribute name="fecha" type="xs:date" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="accesorios" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="matricula" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== luishidalgoo27/2T---Luis-Hidalgo/tema11/concesionariooptimizado.xml
<?xml version="1.0" encoding="UTF-8"?>
<coche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="concesionariooptimizado.xsd" matricula="6732KPC">
    <marca>Seat</marca>
    <modelo>Ateca</modelo>
    <cilindrada>1.7</cilindrada>
    <combustible>Diesel</combustible>
    <precio>23.000€</precio>
    <año>2018</año>
    <color>Negro</color>
    <interesado>33358697A</interesado>
    <interesado>30515455T</interesado>
    <fecha_limite fecha="2022-02-12"/>
    <accesorios>baca llantas navegador</accesorios>
</coche>
